import Foundation
import SwiftData

// MARK: - User
struct User: Identifiable, Codable {
    let id: String
    let email: String
    let fullName: String
    let username: String
    let language: String
    let leaderboardScore: Int
    
    // Mock current user
    static let currentUser = User(
        id: "user_123",
        email: "demo@example.com",
        fullName: "Demo User",
        username: "demouser",
        language: "en",
        leaderboardScore: 1250
    )
}

// MARK: - Calendar Event
enum EventType: String, Codable, CaseIterable {
    case meal
    case workout
    case work
    case sleep
    case freeWrite = "free_write"
    case todo
    
    var iconName: String {
        switch self {
        case .meal: return "fork.knife"
        case .workout: return "dumbbell.fill"
        case .work: return "briefcase.fill"
        case .sleep: return "bed.double.fill"
        case .freeWrite: return "book.fill"
        case .todo: return "checkmark.circle.fill"
        }
    }
}

struct CalendarEvent: Identifiable, Codable {
    let id: UUID
    var title: String
    var type: EventType
    var startTime: Date
    var endTime: Date
    var date: Date
    var isAutoGenerated: Bool
    var scheduleId: UUID?
    var linkedRecipeId: UUID?
    var recipeTitle: String?
    
    init(id: UUID = UUID(), title: String, type: EventType, startTime: Date, endTime: Date, date: Date, isAutoGenerated: Bool = false, scheduleId: UUID? = nil, linkedRecipeId: UUID? = nil, recipeTitle: String? = nil) {
        self.id = id
        self.title = title
        self.type = type
        self.startTime = startTime
        self.endTime = endTime
        self.date = date
        self.isAutoGenerated = isAutoGenerated
        self.scheduleId = scheduleId
        self.linkedRecipeId = linkedRecipeId
        self.recipeTitle = recipeTitle
    }
}

// MARK: - Social Connection
enum ConnectionStatus: String, Codable {
    case pendingSent = "pending_sent"
    case pendingReceived = "pending_received"
    case accepted
}

struct SocialConnection: Identifiable, Codable {
    let id: UUID
    let createdBy: String
    let friendEmail: String
    let friendName: String
    let friendUsername: String
    var status: ConnectionStatus
}

// MARK: - Workout Streak
struct WorkoutStreak: Identifiable, Codable {
    let id: UUID
    let myCurrentStreak: Int
    let friendCurrentStreak: Int
    let myLastWorkout: Date?
    let friendLastWorkout: Date?
    let competitionStartDate: Date
}

// MARK: - Social Post
struct SocialPost: Identifiable, Codable {
    let id: UUID
    let createdBy: String // Email
    let createdByName: String
    let createdDate: Date
    let content: String
    let imageUrl: String?
    var likes: Int
    var comments: Int
}

// MARK: - Achievement
struct ActivityFeedItem: Identifiable, Codable {
    let id: UUID
    let createdBy: String
    let createdByName: String
    let activityDate: Date
    let type: String // e.g., "workout_complete", "streak_milestone"
    let title: String
    let description: String
    let data: [String: String]? // Flexible data payload
}

// MARK: - Group Challenge
enum ChallengeCategory: String, Codable, CaseIterable {
    case exercise
    case diet
    case sleep
    case productivity
    case mentalHealth = "mental_health"
}

enum ChallengeType: String, Codable, CaseIterable {
    case streak
    case totalCount = "total_count"
    case weeklyGoal = "weekly_goal"
}

struct ChallengeParticipant: Identifiable, Codable {
    let id: UUID
    let userEmail: String
    let userName: String
    var currentProgress: Int
    let joinedDate: Date
    
    init(id: UUID = UUID(), userEmail: String, userName: String, currentProgress: Int, joinedDate: Date) {
        self.id = id
        self.userEmail = userEmail
        self.userName = userName
        self.currentProgress = currentProgress
        self.joinedDate = joinedDate
    }
}

struct GroupChallenge: Identifiable, Codable {
    let id: UUID
    let title: String
    let description: String
    let category: ChallengeCategory
    let challengeType: ChallengeType
    let targetValue: Int
    let durationDays: Int
    let startDate: Date
    let endDate: Date
    var participants: [ChallengeParticipant]
    var status: String // "active", "completed"
}

// MARK: - Fitness Models
enum MuscleGroup: String, Codable, CaseIterable {
    case chest, back, shoulders, arms, core, legs
    case traps, forearms, glutes, hamstrings, calves
    
    var displayName: String {
        self.rawValue.capitalized
    }
}

// MARK: - Phase 3 Models

// MARK: - Blu Customization
struct BluCustomization: Codable {
    var expression: String // "happy", "excited", "focused", "chill", "determined"
    var outfit: String // "casual", "sporty", "formal", "superhero", "sleepwear"
    var accessory: String // "none", "glasses", "headband", "cap", "crown"
    var hair: String // "short", "spiky", "wavy", "mohawk", "bald"
    var color: String // "blue", "purple", "green", "orange", "pink"
    var stance: String // "standing", "squatting", "pushup", "stretching", "sitting"
    
    static let defaultCustomization = BluCustomization(
        expression: "happy",
        outfit: "casual",
        accessory: "none",
        hair: "short",
        color: "blue",
        stance: "standing"
    )
}

// MARK: - Sleep Schedule (SwiftData)
@Model
class SleepSchedule {
    @Attribute(.unique) var id: UUID
    var name: String
    var bedtime: Date
    var wakeTime: Date
    var days: [String] // "mon", "tue", etc.
    var isEnabled: Bool
    
    // New properties for alarm logic
    var offTaskType: String // "none", "math", "typing"
    var taskDifficulty: String // "easy", "medium", "difficult"
    var alarmSound: String
    var useSmartAlarm: Bool
    var syncToCalendar: Bool
    
    init(id: UUID = UUID(), 
         name: String, 
         bedtime: Date, 
         wakeTime: Date, 
         days: [String], 
         isEnabled: Bool,
         offTaskType: String = "none",
         taskDifficulty: String = "medium",
         alarmSound: String = "Default",
         useSmartAlarm: Bool = false,
         syncToCalendar: Bool = false) {
        self.id = id
        self.name = name
        self.bedtime = bedtime
        self.wakeTime = wakeTime
        self.days = days
        self.isEnabled = isEnabled
        self.offTaskType = offTaskType
        self.taskDifficulty = taskDifficulty
        self.alarmSound = alarmSound
        self.useSmartAlarm = useSmartAlarm
        self.syncToCalendar = syncToCalendar
    }
}

// MARK: - Todo Item (SwiftData)
@Model
class TodoItem: Identifiable {
    var id: UUID = UUID()
    var text: String
    var isCompleted: Bool
    var order: Int
    var date: Date?
    var sourceRoadmapId: UUID?
    var sourceDayNumber: Int?
    
    init(id: UUID = UUID(), text: String, isCompleted: Bool, order: Int, date: Date? = nil, sourceRoadmapId: UUID? = nil, sourceDayNumber: Int? = nil) {
        self.id = id
        self.text = text
        self.isCompleted = isCompleted
        self.order = order
        self.date = date
        self.sourceRoadmapId = sourceRoadmapId
        self.sourceDayNumber = sourceDayNumber
    }
}

// MARK: - AI Workout Plan
struct AIWorkoutPlan: Identifiable, Codable {
    let id: UUID
    let planName: String
    let goal: String
    let durationWeeks: Int
    let workoutsPerWeek: Int
    let workoutDurationMinutes: Int
    let weeklySchedule: [WeeklyWorkout]
    var isActive: Bool
    let startDate: Date
}

struct WeeklyWorkout: Codable {
    let day: String
    let workoutName: String
    let exercises: [String]
    let notes: String
}

// MARK: - Phase 4 Models

// MARK: - Recipe & Nutrition (SwiftData)
// Recipe & NutritionInfo removed to avoid ambiguity with new Struct versions
// @Model class Recipe ...


@Model
class MealPlan {
    @Attribute(.unique) var id: UUID
    var planName: String
    var startDate: Date
    var endDate: Date
    var dietaryPreferences: [String]
    var dailyCalorieGoal: Double
    var mealsPerDay: Int
    var weeklyMeals: [DailyMealPlan]
    var groceryList: [GroceryItem]
    var isActive: Bool
    var aiGenerated: Bool
    
    init(id: UUID = UUID(), planName: String, startDate: Date, endDate: Date, dietaryPreferences: [String], dailyCalorieGoal: Double, mealsPerDay: Int, weeklyMeals: [DailyMealPlan], groceryList: [GroceryItem], isActive: Bool, aiGenerated: Bool) {
        self.id = id
        self.planName = planName
        self.startDate = startDate
        self.endDate = endDate
        self.dietaryPreferences = dietaryPreferences
        self.dailyCalorieGoal = dailyCalorieGoal
        self.mealsPerDay = mealsPerDay
        self.weeklyMeals = weeklyMeals
        self.groceryList = groceryList
        self.isActive = isActive
        self.aiGenerated = aiGenerated
    }
}

struct DailyMealPlan: Codable {
    let day: String // monday, tuesday, etc.
    let meals: [PlannedMeal]
}

struct PlannedMeal: Codable {
    let mealType: String // breakfast, lunch, dinner, snack
    let recipeId: String
    let recipeTitle: String
    let calories: Double
    let protein: Double
    let carbs: Double
    let fat: Double
}

struct GroceryItem: Codable {
    let ingredient: String
    let quantity: String
    let category: String
}

// MARK: - Fitness (Detailed)
struct Exercise: Identifiable, Codable {
    let id: UUID
    let exerciseName: String
    let videoUrl: String?
    let thumbnailUrl: String?
    let primaryMuscleGroup: String
    let secondaryMuscles: String?
    let requiredEquipment: String?
}

struct Workout: Identifiable, Codable {
    let id: UUID
    let workoutName: String
    let description: String
    let category: String
    let exercises: [WorkoutExercise]
    let estimatedDuration: String
}

struct WorkoutExercise: Codable {
    let exerciseId: String
    let setsAndReps: String
    let restTime: Double
    let setType: String // Normal, Warm-up, Drop Set, Failure Set
}

@Model
class WorkoutSession {
    @Attribute(.unique) var id: UUID
    var workoutId: String
    var workoutName: String
    var dateCompleted: Date
    var exercisesCompleted: [CompletedExercise]
    var totalVolume: Double
    var durationMinutes: Double
    var personalNote: String?
    var status: String // in_progress, completed, skipped
    
    init(id: UUID = UUID(), workoutId: String, workoutName: String, dateCompleted: Date, exercisesCompleted: [CompletedExercise], totalVolume: Double, durationMinutes: Double, personalNote: String? = nil, status: String) {
        self.id = id
        self.workoutId = workoutId
        self.workoutName = workoutName
        self.dateCompleted = dateCompleted
        self.exercisesCompleted = exercisesCompleted
        self.totalVolume = totalVolume
        self.durationMinutes = durationMinutes
        self.personalNote = personalNote
        self.status = status
    }
}

struct CompletedExercise: Codable {
    let exerciseId: String
    let exerciseName: String
    let sets: [CompletedSet]
}

struct CompletedSet: Codable {
    let weight: Double
    let reps: Double
    let setType: String
}

@Model
class BodyMeasurement {
    @Attribute(.unique) var id: UUID
    var date: Date
    var weight: Double
    var bodyFatPercentage: Double?
    var chest: Double?
    var waist: Double?
    var hips: Double?
    var bicepLeft: Double?
    var bicepRight: Double?
    var thighLeft: Double?
    var thighRight: Double?
    var notes: String?
    
    init(id: UUID = UUID(), date: Date, weight: Double, bodyFatPercentage: Double? = nil, chest: Double? = nil, waist: Double? = nil, hips: Double? = nil, bicepLeft: Double? = nil, bicepRight: Double? = nil, thighLeft: Double? = nil, thighRight: Double? = nil, notes: String? = nil) {
        self.id = id
        self.date = date
        self.weight = weight
        self.bodyFatPercentage = bodyFatPercentage
        self.chest = chest
        self.waist = waist
        self.hips = hips
        self.bicepLeft = bicepLeft
        self.bicepRight = bicepRight
        self.thighLeft = thighLeft
        self.thighRight = thighRight
        self.notes = notes
    }
}

struct RunRecord: Identifiable, Codable {
    let id: UUID
    let runKey: String
    let displayName: String
    let distanceKm: Double
    let lastRunSeconds: Double
    let lastRunDate: Date
    let personalBestSeconds: Double?
    let routeData: [[Double]] // [[lat, lon]]
    let avgPace: String
    let caloriesBurned: Double
}

// MARK: - Habits (SwiftData)
@Model
class Habit {
    @Attribute(.unique) var id: UUID
    var name: String
    var descriptionText: String // Renamed from description to avoid conflict
    var habitType: String
    var category: String
    var icon: String
    var color: String
    var frequencyType: String
    var targetDays: [String]
    var targetCount: Double
    var targetUnit: String?
    var reminderEnabled: Bool
    var reminderTimes: [String]
    var currentStreak: Int
    var bestStreak: Int
    var totalCompletions: Int
    var isActive: Bool
    
    @Relationship(deleteRule: .cascade) var logs: [HabitLog] = []
    
    init(id: UUID = UUID(), name: String, descriptionText: String, habitType: String, category: String, icon: String, color: String, frequencyType: String, targetDays: [String], targetCount: Double, targetUnit: String? = nil, reminderEnabled: Bool, reminderTimes: [String], currentStreak: Int, bestStreak: Int, totalCompletions: Int, isActive: Bool) {
        self.id = id
        self.name = name
        self.descriptionText = descriptionText
        self.habitType = habitType
        self.category = category
        self.icon = icon
        self.color = color
        self.frequencyType = frequencyType
        self.targetDays = targetDays
        self.targetCount = targetCount
        self.targetUnit = targetUnit
        self.reminderEnabled = reminderEnabled
        self.reminderTimes = reminderTimes
        self.currentStreak = currentStreak
        self.bestStreak = bestStreak
        self.totalCompletions = totalCompletions
        self.isActive = isActive
    }
}

@Model
class HabitLog {
    @Attribute(.unique) var id: UUID
    var date: Date
    var completed: Bool
    var count: Double
    var journalEntry: String?
    var mood: String?
    var notes: String?
    
    var habit: Habit?
    
    init(id: UUID = UUID(), date: Date, completed: Bool, count: Double, journalEntry: String? = nil, mood: String? = nil, notes: String? = nil) {
        self.id = id
        self.date = date
        self.completed = completed
        self.count = count
        self.journalEntry = journalEntry
        self.mood = mood
        self.notes = notes
    }
}

// MARK: - Content & Social
struct Playlist: Identifiable, Codable {
    let id: UUID
    let name: String
    let description: String
    let service: String // spotify, apple_music, custom
    let playlistUrl: String?
    let coverColor: String
    let category: String
    let tracks: [Track]
}

struct Track: Codable {
    let title: String
    let artist: String
    let duration: Double
    let bpm: Double?
}

struct SavedItem: Identifiable, Codable {
    let id: UUID
    let itemType: String // recipe, workout, etc.
    let itemId: String
    let itemName: String
    let tags: [String]
    let notes: String?
}

@Model
class SavedRecipe {
    @Attribute(.unique) var recipeId: UUID
    var title: String
    var savedDate: Date
    
    init(recipeId: UUID, title: String, savedDate: Date = Date()) {
        self.recipeId = recipeId
        self.title = title
        self.savedDate = savedDate
    }
}

struct Report: Identifiable, Codable {
    let id: UUID
    let reportedUserEmail: String
    let reason: String
    let details: String?
    let status: String
}

// MARK: - AI Chat
@Model
class ChatMessage {
    @Attribute(.unique) var id: UUID
    var text: String
    var isUser: Bool
    var timestamp: Date
    
    init(id: UUID = UUID(), text: String, isUser: Bool, timestamp: Date) {
        self.id = id
        self.text = text
        self.isUser = isUser
        self.timestamp = timestamp
    }
}

// MARK: - Recipes
struct NutritionInfo: Codable, Hashable {
    var calories: Int
    var protein: Int
    var carbs: Int
    var fat: Int
    var fiber: Int = 0
    var sugar: Int = 0
    var sodium: Int = 0
}

struct RecipeModel: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var title: String
    var description: String = ""
    var image: String
    var time: String
    var servings: String = "1"
    var difficulty: String = "Medium"
    var category: String
    
    var ingredients: [String]
    var instructions: [String]
    var nutrition: NutritionInfo
    
    var tags: [String] = []
    var isSaved: Bool = false
    
    func matches(_ query: String) -> Bool {
        query.isEmpty || title.localizedCaseInsensitiveContains(query) || ingredients.contains { $0.localizedCaseInsensitiveContains(query) }
    }
}
@Model
class PantryItem {
    @Attribute(.unique) var id: UUID
    var name: String
    var category: String
    var quantity: Double
    var unit: String
    var addedDate: Date
    
    init(id: UUID = UUID(), name: String, category: String, quantity: Double, unit: String, addedDate: Date = Date()) {
        self.id = id
        self.name = name
        self.category = category
        self.quantity = quantity
        self.unit = unit
        self.addedDate = addedDate
    }
}

@Model
class CartItem {
    @Attribute(.unique) var id: UUID
    var name: String
    var category: String
    var quantity: Double
    var unit: String
    
    init(id: UUID = UUID(), name: String, category: String, quantity: Double, unit: String) {
        self.id = id
        self.name = name
        self.category = category
        self.quantity = quantity
        self.unit = unit
    }
}

// MARK: - Analytics Historical Tracking Models

@Model
class DailyNutritionLog {
    @Attribute(.unique) var id: UUID
    var date: Date
    var calories: Double
    var protein: Double
    var carbs: Double
    var fat: Double
    
    init(id: UUID = UUID(), date: Date, calories: Double, protein: Double, carbs: Double, fat: Double) {
        self.id = id
        self.date = date
        self.calories = calories
        self.protein = protein
        self.carbs = carbs
        self.fat = fat
    }
    
    // Helper to get or create log for a specific date
    static func normalizedDate(_ date: Date) -> Date {
        Calendar.current.startOfDay(for: date)
    }
}

@Model
class SleepLog {
    @Attribute(.unique) var id: UUID
    var date: Date // Start of night
    var durationHours: Double
    var qualityScore: Int // 0-100
    var deepSleepMinutes: Int?
    var remSleepMinutes: Int?
    
    init(id: UUID = UUID(), date: Date, durationHours: Double, qualityScore: Int, deepSleepMinutes: Int? = nil, remSleepMinutes: Int? = nil) {
        self.id = id
        self.date = date
        self.durationHours = durationHours
        self.qualityScore = qualityScore
        self.deepSleepMinutes = deepSleepMinutes
        self.remSleepMinutes = remSleepMinutes
    }
}

@Model
class ExerciseLog {
    @Attribute(.unique) var id: UUID
    var date: Date
    var steps: Int
    var activeCalories: Int
    var exerciseMinutes: Int
    
    init(id: UUID = UUID(), date: Date, steps: Int, activeCalories: Int, exerciseMinutes: Int) {
        self.id = id
        self.date = date
        self.steps = steps
        self.activeCalories = activeCalories
        self.exerciseMinutes = exerciseMinutes
    }
}

@Model
class ScreenTimeLog {
    @Attribute(.unique) var id: UUID
    var date: Date
    var totalMinutes: Int
    var categoryBreakdown: [String: Int] // categoryName: minutes
    
    init(id: UUID = UUID(), date: Date, totalMinutes: Int, categoryBreakdown: [String: Int]) {
        self.id = id
        self.date = date
        self.totalMinutes = totalMinutes
        self.categoryBreakdown = categoryBreakdown
    }
}
